[project]
name = "pwnflow-ai-schemas"
version = "0.1.0"
description = "Shared AI schema models for Pwnflow services"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
